---
name: 'GUAC Ingest'
description: 'Ingest files into GUAC'
branding:
  icon: "shield"
  color: "purple"
author: 'Kusari'
inputs:
  files:
    description: 'Path to directory or specific file to ingest'
    required: true
  api-addr:
    description: 'Kusari hosted GUAC tenant api endpoint'
    required: true
  client-id:
    description: 'Client id for auth token provider'
    required: true
  client-secret:
    description: 'Client secret for auth token provider'
    required: true
  token-url:
    description: 'Url for auth token provider'
    required: true
    default: https://auth.us.kusari.cloud/oauth2/token
outputs:
  console_out:
    description: 'GUAC ingestion output'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.files }}
    - ${{ inputs.client-id }}
    - ${{ inputs.client-secret }}
    - ${{ inputs.api-addr }}
    - ${{ inputs.token-url }}
